---
- name: Create a Quadlet file
  become: true
  containers.podman.podman_container:
    name: syncthing
    hostname: "{{ inventory_hostname }}"
    image: lscr.io/linuxserver/syncthing:{{ syncthing_version }}
    state: quadlet
    quadlet_filename: syncthing-container
    network: slirp4netns
    ports:
      - 8384:8384
    volumes:
      - /var/opt/syncthing:/config:rw
    env:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    quadlet_options:
      - AutoUpdate=registry
      - Pull=always
      - |
        [Unit]
        After=network-online.target nss-lookup.target
        [Install]
        WantedBy=default.target
  notify:
    - Reload systemd for syncthing
    - Restart syncthing
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
