---
- name: Configure system
  hosts: mini
  vars_files:
    - vars/public.yml
    - vars/vault.yml
  roles:
    - role: reverse_proxy
    - role: backups
    - role: admin
    - role: version_control
    - role: photos
    - role: feed_reader
    - role: bookmarks
    - role: microblogging
    - role: media
    - role: file_sync
    - role: mounts
    # Was unable to get this to work with my autofs/cifs mount
    # https://github.com/kieraneglin/pinchflat/issues/139
    # Putting on hold until I can download to a temp directory:
    #    - role: tube_download
    - role: recipes
    - role: email_client
  tasks:
    - name: Add podman cleanup job
      become: true
      ansible.builtin.cron:
        name: Cleanup dangling podman extras
        minute: "0"
        hour: "3"
        day: "*"
        month: "*"
        weekday: "0"
        job: podman volume prune -f >> /dev/null && podman image prune -af >> /dev/null
