---
- name: Configure system
  hosts: mini
  vars_files:
    - vars/public.yml
    - vars/vault.yml
  roles:
    - role: credentials
    - role: reverse_proxy
    - role: backups
    - role: vms
    - role: admin
    - role: version_control
    - role: photos
    - role: feed_reader
    - role: microblogging
    - role: media
    - role: file_sync
    - role: notifications
    - role: private
    - role: links
    - role: ai_client
  tasks:
    - name: Add podman cleanup job
      become: true
      ansible.builtin.cron:
        name: Cleanup dangling podman extras
        minute: "0"
        hour: "3"
        day: "*"
        month: "*"
        weekday: "0"
        job: podman volume prune -f &> /dev/null && podman image prune -af &> /dev/null
    - name: Add podman cleanup job (user)
      become: false
      ansible.builtin.cron:
        name: Cleanup dangling podman extras
        minute: "0"
        hour: "3"
        day: "*"
        month: "*"
        weekday: "0"
        job: podman volume prune -f &> /dev/null && podman image prune -af &> /dev/null
