---
- name: Reload systemd for wishthis
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
  changed_when: true
- name: Restart wishthis
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  become: true
  loop: "{{ services }}"
