---
- name: Ensure karakeep network is created
  become: true
  containers.podman.podman_network:
    name: karakeep
    state: present
- name: Create a Quadlet file
  become: true
  containers.podman.podman_container:
    name: karakeep-meilisearch
    image: docker.io/getmeili/meilisearch:{{ karakeep_meilisearch_version }}
    state: quadlet
    quadlet_filename: karakeep-meilisearch-container
    network: karakeep
    volumes:
      - /var/opt/karakeep-meilisearch:/meili_data:rw
    env:
      MEILI_NO_ANALYTICS: "true"
      HOARDER_VERSION: release
      NEXTAUTH_SECRET: "{{ karakeep_nextauth_secret }}"
      MEILI_MASTER_KEY: "{{ karakeep_meili_master_key }}"
      NEXTAUTH_URL: http://localhost:3000
    quadlet_options:
      - AutoUpdate=registry
      - Pull=always
      - |
        [Unit]
        After=network-online.target nss-lookup.target
        [Install]
        WantedBy=default.target
  notify:
    - Reload systemd for karakeep
    - Restart karakeep
- name: Create a Quadlet file
  become: true
  containers.podman.podman_container:
    name: karakeep-chrome
    image: gcr.io/zenika-hub/alpine-chrome:{{ karakeep_chrome_version }}
    state: quadlet
    quadlet_filename: karakeep-chrome-container
    network: karakeep
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    quadlet_options:
      - AutoUpdate=registry
      - Pull=always
      - |
        [Unit]
        After=network-online.target nss-lookup.target
        [Install]
        WantedBy=default.target
  notify:
    - Reload systemd for karakeep
    - Restart karakeep
- name: Create a Quadlet file
  become: true
  containers.podman.podman_container:
    name: karakeep-server
    image: ghcr.io/karakeep-app/karakeep:{{ karakeep_server_version }}
    state: quadlet
    quadlet_filename: karakeep-server-container
    network: karakeep
    ports:
      - 127.0.0.1:{{ karakeep_port }}:3000
    stop_time: 30
    volumes:
      - /var/opt/karakeep-server:/data
    env:
      HOARDER_VERSION: release
      NEXTAUTH_SECRET: "{{ karakeep_nextauth_secret }}"
      MEILI_MASTER_KEY: "{{ karakeep_meili_master_key }}"
      NEXTAUTH_URL: http://localhost:3000
      MEILI_ADDR: http://karakeep-meilisearch:7700
      BROWSER_WEB_URL: http://karakeep-chrome:9222
      OPENAI_API_KEY: "{{ karakeep_openai_key }}"
      DATA_DIR: /data
      CRAWLER_FULL_PAGE_SCREENSHOT: "true"
      CRAWLER_FULL_PAGE_ARCHIVE: "true"
      CRAWLER_VIDEO_DOWNLOAD: "true"
      CRAWLER_VIDEO_DOWNLOAD_MAX_SIZE: 250
      DISABLE_SIGNUPS: "true"
    quadlet_options:
      - AutoUpdate=registry
      - Pull=always
      - |
        [Unit]
        [Unit]
        After=karakeep-chrome.service karakeep-meilisearch.service network-online.target nss-lookup.target
        [Install]
        WantedBy=default.target
  notify:
    - Reload systemd for karakeep
    - Restart karakeep
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
