---
- name: Create a Quadlet file
  become: true
  containers.podman.podman_container:
    name: grocy
    image: lscr.io/linuxserver/grocy:{{ freshrss_version }}
    state: quadlet
    quadlet_filename: grocy-container
    network: slirp4netns
    ports:
      - 8087:80
    volumes:
      - /var/opt/grocy:/config:rw
    env:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    quadlet_options:
      - AutoUpdate=registry
      - Pull=always
      - |
        [Unit]
        After=network-online.target nss-lookup.target
        [Install]
        WantedBy=default.target
  notify:
    - Reload systemd for grocy
    - Restart grocy
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
