---
- name: Ensure mount dirs exist
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
  loop:
    - /media/issd2
    - /media/essd1
- name: Check if mergerfs is installed
  become: true
  ansible.builtin.command: rpm -q mergerfs
  register: mergerfs_check
  ignore_errors: true
  changed_when: false
- name: Download mergerfs
  become: true
  ansible.builtin.get_url:
    url: "{{ mergerfs_rpm_url }}"
    dest: "{{ mergerfs_rpm_file }}"
  when: mergerfs_check.rc != 0
- name: Install mergerfs
  become: true
  ansible.builtin.dnf:
    name: "{{ mergerfs_rpm_file }}"
    state: present
  when: mergerfs_check.rc != 0
- name: Remove mergerfs rpm after install
  become: true
  ansible.builtin.file:
    path: "{{ mergerfs_rpm_file }}"
    state: absent
  when: mergerfs_check.rc != 0
- name: Mount MergerFS
  become: true
  ansible.posix.mount:
    path: /mnt
    src: "/media/*"
    fstype: fuse.mergerfs
    opts: allow_other,use_ino,cache.files=off,category.create=pfrd,func.getattr=newest,dropcacheonclose=false
    state: mounted
- name: Mount internal drive
  become: true
  ansible.builtin.mount:
    path: /media/issd2
    src: UUID=e7c76703-b8a6-45e3-99b8-6238adb4df16
    fstype: auto
    opts: nofail
    state: mounted
- name: Mount internal drive
  become: true
  ansible.builtin.mount:
    path: /media/essd1
    src: UUID=d39215ac-c72d-40bc-be53-353d9ef8bea6
    fstype: auto
    opts: nofail
    state: mounted
- name: Ensure systemd override directory exists
  become: true
  ansible.builtin.file:
    path: /etc/systemd/system/smartd.service.d
    state: directory
    mode: "0755"
    owner: root
    group: root
- name: Create systemd override for smartd
  become: true
  ansible.builtin.copy:
    dest: /etc/systemd/system/smartd.service.d/override.conf
    content: |
      [Service]
      TimeoutStartSec=180
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload systemd for smartd
    - Restart smartd
