---
- name: Allow Syncthing
  become: true
  community.general.ufw:
    rule: allow
    comment: "Syncthing TCP Port"
    proto: tcp
    port: 22000
- name: Allow Syncthing
  become: true
  community.general.ufw:
    rule: allow
    comment: "Syncthing UDP Port"
    proto: udp
    port: 22000
- name: Allow Syncthing
  become: true
  community.general.ufw:
    rule: allow
    comment: "Syncthing UDP Port"
    proto: udp
    port: 21027
- name: Create a Quadlet file
  become: true
  containers.podman.podman_container:
    name: syncthing
    hostname: "{{ inventory_hostname }}"
    image: lscr.io/linuxserver/syncthing:{{ syncthing_version }}
    state: quadlet
    quadlet_filename: syncthing-container
    network: slirp4netns
    ports:
      - 127.0.0.1:{{ syncthing_port }}:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    volumes:
      - /var/opt/syncthing:/config:rw
    env:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    quadlet_options:
      - AutoUpdate=registry
      - Pull=always
      - |
        [Unit]
        After=network-online.target nss-lookup.target
        [Service]
        Restart=always
        [Install]
        WantedBy=default.target
  notify:
    - Reload systemd for syncthing
    - Restart syncthing
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
